apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-mani
  namespace: my-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
           - containerPort: 80
          volumeMounts:
           - name: custom-html-pages
             mountPath: /usr/share/nginx/html
      volumes:
        - name: custom-html-pages
          configMap:
            name: my-html-files

